### ISSUE TITLE
HTTP Server Error 500

### ISSUE THREAD

**Issue by dagohbah** [jedi-gg/swgoh.gg.public#359]
Hello all,

I have two profiles, one profile per in-game account. When I login with my one email address and one in game account, it works fine. If I try logging into the second one, it bombs out with an error 500 after clicking on "Login". Is this a known issue? Is there something wrong with my account?

Here's the account that I'm having a problem with: https://swgoh.gg/u/darthrayden/

Thanks!

**Comment by sanktanglia** [comment]
Its most likely just an issue with our data that should be fixed up with our new code update coming out in the next few days

**Comment by dagohbah** [comment]
Understood. I will have to check on it to see if it is still erring after the new update. Thanks so much! @sanktanglia

**Comment by danpaulson** [comment]
How’s this working now?

**Comment by dagohbah** [comment]
@sanktanglia and @danpaulson:

This is still not working for me. Getting a level 500 error page when I try to login.

**Comment by danpaulson** [comment]
Somehow had two accounts with the same email - give it another go now.

**Comment by dagohbah** [comment]
OK, that was it. I can login with both accounts successfully now. Thank you so much! :)
